name: filmflex
description: "A new Flutter project."
publish_to: 'none'
version: 0.9.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_carousel: ^0.1.0+1
  overlapped_carousel: ^1.0.2
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/